[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "./bin/thrust ./bin/rails server -b 0.0.0.0 -p ${PORT:-80}"
